### ISSUE TITLE
I m new in Laravel please help

### ISSUE THREAD

**Issue by coolsharad** [appstract/laravel-moneybird#5]
Hi 

  First of all sorry for English, I m pretty new in laravel i have installed your package but how i use your package in controller , right now in example you direct paste $contact = Moneybird::contact(); do we need to include anything in controller , Use Appstract\Moneybird like that , Can you help me on this 

Thanks

**Comment by gizburdt** [comment]
Put `use Moneybird;` at the top of the file :)

**Comment by coolsharad** [comment]
@gizburdt Thanks for your fast reply

**Comment by coolsharad** [comment]
@gizburdt  I m working on localhost so in redirect uri what i need to add in url?
