### ISSUE TITLE
Redirect Uri

### ISSUE THREAD

**Issue by coolsharad** [appstract/laravel-moneybird#6]
Hi 
  Once package is published and config file is created under config folder , in Uri fileds it showing some uncoding uri do we need to remove this and current url , i m facing authentication problem once i add client id client_secret , please tell me what i need to add in that field

Thanks

**Comment by gizburdt** [comment]
Please check documentation:

- https://github.com/picqer/moneybird-php-client
- https://developer.moneybird.com/
