### ISSUE TITLE
Regarding Authorization Code Url

### ISSUE THREAD

**Issue by coolsharad** [appstract/laravel-moneybird#7]
Hi 
  I have to create access token with Authorization Code , i m getting code on particular url and now i have to set authorization code and generate access token and create a invoice and you give me some example how to do it in laravel , i m pretty new in laravel

Thanks  in Adavance

**Comment by gizburdt** [comment]
Hi,

Something like this:

```
$invoice = Moneybird::salesInvoice()->create();

$invoice->reference = '123456';

$invoice->save();
```

For more information, please have a look at picqer/moneynbird-php-client and the Moneybird docs. This package is only a wrapper for these libraries.

**Comment by coolsharad** [comment]
Basically i just need connection object while redirect with Authorisation Code on particular root
